[pkg]added experimental glibc, various kernels, retroarch

diff --git a/src/kernel/kernel/kernel.SlackBuild b/src/kernel/kernel/kernel.SlackBuild
--- a/src/kernel/kernel/kernel.SlackBuild
+++ b/src/kernel/kernel/kernel.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-# Slackware build script for vice
+# Slackware build script for kernel
 
-# Copyright 2019 Michele Zuccalà < ardutu at gmail dot com >
+# Copyright 2020 Michele Zuccalà < ardutu at gmail dot com >
 # All rights reserved
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,7 +27,7 @@ if [ $UID != "0" ]; then
     exit 1
 fi
 
-PRGNAM=vice
+PRGNAM=kernel
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-$PRGNAM
@@ -72,9 +72,9 @@ fi
 
 set -e
 
-SOURCE_TAR=`basename $DOWNLOAD_URL`
+SOURCE_TAR=${SOURCE_TAR:-`basename $DOWNLOAD_URL`}
 if [ ! -e ${CWD}/$SOURCE_TAR ]; then
-  wget -c $DOWNLOAD_URL
+  wget -c $DOWNLOAD_URL -O $SOURCE_TAR
 fi
 
 if [ ! $DOWNLOAD_SHA1 == `sha1sum $SOURCE_TAR | cut -d " " -f 1` ]; then
@@ -87,63 +87,28 @@ mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$SOURCE_TAR
-cd $PRGNAM-$VERSION
+cd $SRCNAM
 chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+#find -L . \
+# \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
+#  -o -perm 511 \) -exec chmod 755 {} \; -o \
+# \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
+#  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-#apply patches
-for i in `find $CWD/patches/ -name *.patch | sort -`; do
-    patch -p1 < $i
-done
+if [ ! -e $CWD/kernel_config ]; then
+    echo "config for kernel not found!!"
+    exit 1
+fi
 
-sed -i 's/lib64/lib/g' configure.ac
-autoreconf -fi
+cp $CWD/kernel_config .config
+make -j3 ARCH=$ARCH CROSS_COMPILE=$SLK_TARGET- all
+make -j3 ARCH=$ARCH CROSS_COMPILE=$SLK_TARGET- INSTALL_MOD_PATH=$PKG/ modules_install
 
-CFLAGS="$SLK_CFLAGS $SYSROOT -s  " \
-CXXFLAGS="$SLK_CFLAGS $SYSROOT -s  " \
-LDFLAGS="$SYSROOT -lcrypto" \
-PATH=$SLK_SYSROOT/usr/bin:$PATH \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib \
-  --bindir=/usr/bin \
-  --sbindir=/usr/sbin \
-  --sysconfdir=/etc \
-  --localstatedir=/var \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/$PRGNAM-$VERSION \
-  --includedir=/usr/include \
-  --disable-realdevice \
-  --without-resid \
-  --disable-catweasel \
-  --disable-midi \
-  --enable-sdlui2 \
-  --without-oss \
-  $TARGET
-
-# fix error
-sed -i 's/\-Werror\=implicit\-function\-declaration//g' Makefile
-
-make -j2 V=0
-make DESTDIR=$PKG install
-
-set -e
-#strip binaries
-( cd $PKG
-  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
-  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
-)
-
-# install docs
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a AUTHORS COPYING FEEDBACK INSTALL NEWS README doc $PKG/usr/doc/$PRGNAM-$VERSION
+mkdir -p $PKG/boot
+cp arch/$ARCH/boot/bzImage $PKG/boot/vmlinuz
 
 mkdir -p $PKG/install
+#cat $CWD/doinst.sh > $PKG/install/doinst.sh
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 #generate slack-required
