[pkg]fix raspberry build, fix init script, added alsa haveged ntp

diff --git a/src/extra/alsa-utils/alsa-utils.SlackBuild b/src/extra/alsa-utils/alsa-utils.SlackBuild
--- a/src/extra/alsa-utils/alsa-utils.SlackBuild
+++ b/src/extra/alsa-utils/alsa-utils.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/sh
 
-# Slackware build script for raspberry-firmware
+# Slackware build script for alsa-utils
 
-# Copyright 2018 Michele Zuccalà < ardutu at gmail dot com >
+# Copyright 2019 Michele Zuccalà < ardutu at gmail dot com >
 # All rights reserved
 #
 # Redistribution and use of this script, with or without modification, is
@@ -27,11 +27,12 @@ if [ $UID != "0" ]; then
     exit 1
 fi
 
-PRGNAM=raspberry-firmware
+PRGNAM=alsa-utils
 CWD=$(pwd)
 TMP=${TMP:-/tmp}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-$PWD}
+ARCH=${ARCH:-`uname -m`}
 
 if [ ! -e $CWD/$PRGNAM.info ]; then
     echo "File $PRGNAM.info not found"
@@ -42,8 +43,7 @@ fi
 
 STRIP_CMD=strip
 if [ ! -z "$SLK_TARGET" ]; then
-    TARGET=" --target=$SLK_TARGET "
-    ARCH=` echo $SLK_TARGET | cut -d - -f 1 -`
+    TARGET=" --host=$SLK_TARGET "
     STRIP_CMD=$SLK_TARGET-strip
 fi
 
@@ -51,11 +51,10 @@ if [ ! -z "$SLK_SYSROOT" ]; then
     SYSROOT=" --sysroot=$SLK_SYSROOT "
 fi
 
-
 case $ARCH in
     i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
-    x86_64) ;; 
+    x86_64) ;;
     *) ARCH=$( uname -m ) ;;
 esac
 
@@ -86,9 +85,9 @@ fi
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf firmware-*
+rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$SOURCE_TAR
-cd firmware-*
+cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
@@ -96,25 +95,39 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# pack blobs
-cp -r boot $PKG/
-mkdir -p $PKG/lib
-cp -r modules $PKG/lib
+CFLAGS="$SLK_CFLAGS $SYSROOT -s" \
+CXXFLAGS="$SLK_CFLAGS $SYSROOT -s " \
+./configure \
+  --prefix=/usr \
+  --disable-static \
+  --libdir=/usr/lib \
+  --bindir=/usr/bin \
+  --sbindir=/usr/sbin \
+  --sysconfdir=/etc \
+  --localstatedir=/var \
+  --mandir=/usr/man \
+  --docdir=/usr/doc/$PRGNAM-$VERSION \
+  --includedir=/usr/include \
+  $TARGET
 
-# compress modules
-echo compressing modules
-find $PKG/lib -name *.ko -exec gzip -v {} \;
-depmod -b $PKG $VERSION+
-depmod -b $PKG $VERSION-v7+
-depmod -b $PKG $VERSION-v7l+
-depmod -b $PKG $VERSION-v8+
+make -j2 V=1
+make DESTDIR=$PKG install
 
-#install configs
-cp $CWD/config.txt $PKG/boot
-cp $CWD/cmdline.txt $PKG/boot
+# cleanup 
+rm -r $PKG/lib
+rm $PKG/usr/sbin/{alsa-info.sh,alsaconf,alsabat-test.sh}
 
+set -e
+#strip binaries
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
+  find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r $STRIP_CMD --strip-unneeded 2> /dev/null || true
+)
+
+# install docs
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -r documentation $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a ChangeLog INSTALL README.md TODO COPYING  $PKG/usr/doc/$PRGNAM-$VERSION
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
@@ -131,9 +144,9 @@ cd $PKG
 mkdir -p $OUTPUT
 
 if [ -z $SLK_ARCH ]; then
-    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+    makepkg -l n -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
 else
-    makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$SLK_ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+    makepkg -l n -c n $OUTPUT/$PRGNAM-$VERSION-$SLK_ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
 fi
 
 # Clean up the extra stuff:
